<a href="https://colab.research.google.com/github/nsaali/ASU-Graduate-Courses/blob/main/Saali_HW4_Eigen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Nick Saali LSC562 HW4

# Number 2

import numpy as np
import matplotlib . pyplot as plt
import scipy . linalg as la 

A = np . array ([[3 ,0 ,-2],[0 ,1 , 2],[0 ,-2 , 1]])
print (A)
eigvals , eigvecs = la . eig (A) # calculatues eigenvalues & eigenvectors of A
print('Ouput / Answers for Number 2')
print ( eigvals )
print ( eigvecs ) # columns are the eigenvectors
realeigs = eigvals . real # this isolates the real part of the eigenvalues
# the above line could be useful to test stability or if you want to
# ignore the 0.j that arises
print ( realeigs )
lambda1 = eigvals [0]
print ( lambda1 )
v1 = eigvecs [:,0]. reshape (3 ,1) # arranges as a column
print ( v1 )
# the next two answers should be identical since A*v= lambda *v
print ( lambda1 * v1 )
print ( np . dot (A , v1 )) # matrix - vector m u l t i p l i c a t i o n
print (A @ v1 ) # also matrix - vector m u l t i p l i c a t i o n
lambda2 = eigvals [1]
print ( lambda2 )
v2 = eigvecs [:,1]. reshape (3 ,1)
print ( lambda2 * v2 )
print (A @ v2 ) # this should equal the previous line since A*v2= lambda2 * v2
lambda3 = eigvals [2]
print ( lambda3 )
v3 = eigvecs [:,2]. reshape (3 ,1)
print ( v3 )
print ( lambda3 * v3 )
print (A @ v3 )


# Number 3

# a

A = np . array ([[1, 3],[3, 1]])
print (A)
eigvals , eigvecs = la . eig (A) 
print ( eigvals )
print ( eigvecs ) 

realeigs = eigvals . real
print('Ouput / Answers for Number 3 a')
print ( realeigs )
lambda1 = eigvals [0]
print ( lambda1 )
v1 = eigvecs [:,0]. reshape (2 ,1) 
print ( v1 )

print ( lambda1 * v1 )
print ( np . dot (A , v1 )) 
print (A @ v1 ) 
lambda2 = eigvals [1]
print ( lambda2 )
v2 = eigvecs [:,1]. reshape (2 ,1)
print ( lambda2 * v2 )
print (A @ v2 ) 

# b

A = np . array ([[-3, -5],[1, -7]])
print (A)
eigvals , eigvecs = la . eig (A) 
print('Ouput / Answers for Number 3 b')
print ( eigvals )
print ( eigvecs ) 

realeigs = eigvals . real
print ( realeigs )
lambda1 = eigvals [0]
print ( lambda1 )
v1 = eigvecs [:,0]. reshape (2 ,1) 
print ( v1 )

print ( lambda1 * v1 )
print ( np . dot (A , v1 )) 
print (A @ v1 ) 
lambda2 = eigvals [1]
print ( lambda2 )
v2 = eigvecs [:,1]. reshape (2 ,1)
print ( lambda2 * v2 )
print (A @ v2 ) 

# c

A = np . array ([[-2 ,2 ,0],[4 ,0 , 0],[-10/3 ,5/3 , 1]])
print (A)
eigvals , eigvecs = la . eig (A) 
print('Ouput / Answers for Number 3 c')
print ( eigvals )
print ( eigvecs ) 
realeigs = eigvals . real 
print ( realeigs )
lambda1 = eigvals [0]
print ( lambda1 )
v1 = eigvecs [:,0]. reshape (3 ,1) 
print ( v1 )
print ( lambda1 * v1 )
print ( np . dot (A , v1 )) 
print (A @ v1 ) 
lambda2 = eigvals [1]
print ( lambda2 )
v2 = eigvecs [:,1]. reshape (3 ,1)
print ( lambda2 * v2 )
print (A @ v2 ) 
lambda3 = eigvals [2]
print ( lambda3 )
v3 = eigvecs [:,2]. reshape (3 ,1)
print ( v3 )
print ( lambda3 * v3 )
print (A @ v3 )

# d

A = np . array ([[1 ,-5 ,-1],[1 ,3 , 1],[0 ,0 , 1]])
print (A)
eigvals , eigvecs = la . eig (A) 
print('Ouput / Answers for Number 3 d')
print ( eigvals )
print ( eigvecs ) 
realeigs = eigvals . real 
print ( realeigs )
lambda1 = eigvals [0]
print ( lambda1 )
v1 = eigvecs [:,0]. reshape (3 ,1) 
print ( v1 )
print ( lambda1 * v1 )
print ( np . dot (A , v1 )) 
print (A @ v1 ) 
lambda2 = eigvals [1]
print ( lambda2 )
v2 = eigvecs [:,1]. reshape (3 ,1)
print ( lambda2 * v2 )
print (A @ v2 ) 
lambda3 = eigvals [2]
print ( lambda3 )
v3 = eigvecs [:,2]. reshape (3 ,1)
print ( v3 )
print ( lambda3 * v3 )
print (A @ v3 )

# e

A = np . array ([[-2/3 ,-2/3 ,0],[-4/3 ,-4/3, 0] ,[2/3 ,-1/3, -1]])
print (A)
eigvals , eigvecs = la . eig (A) 
print('Ouput / Answers for Number 3 e')
print ( eigvals )
print ( eigvecs ) 
realeigs = eigvals . real 
print ( realeigs )
lambda1 = eigvals [0]
print ( lambda1 )
v1 = eigvecs [:,0]. reshape (3 ,1) 
print ( v1 )
print ( lambda1 * v1 )
print ( np . dot (A , v1 )) 
print (A @ v1 ) 
lambda2 = eigvals [1]
print ( lambda2 )
v2 = eigvecs [:,1]. reshape (3 ,1)
print ( lambda2 * v2 )
print (A @ v2 ) 
lambda3 = eigvals [2]
print ( lambda3 )
v3 = eigvecs [:,2]. reshape (3 ,1)
print ( v3 )
print ( lambda3 * v3 )
print (A @ v3 )

# Number 4 

# a

A = np . array ([[-1 ,2 ,0, -1],[-2 ,-1 ,0, 0],[0 ,0, 3,-1], [0,0,-1,3]])
print (A)
eigvals , eigvecs = la . eig (A) 
print('Ouput / Answers for Number 4 a')
print ( eigvals )
print ( eigvecs ) 
realeigs = eigvals . real 
print ( realeigs )
lambda1 = eigvals [0]
print ( lambda1 )

# b

A = np . array ([[-1 ,2 ,0, -1],[-2 ,-1 ,0, 0],[0 ,0, 3,-1], [0,0,1,3]])
print (A)
eigvals , eigvecs = la . eig (A) 
print('Ouput / Answers for Number 4 b')
print ( eigvals )
print ( eigvecs ) 
realeigs = eigvals . real 
print ( realeigs )
lambda1 = eigvals [0]
print ( lambda1 )

# c

A = np . array ([[-1 ,-2 ,0, -1],[-2 ,-1 ,0, 0],[0 ,0, 3,-1], [0,0,1,3]])
print (A)
eigvals , eigvecs = la . eig (A) 
print('Ouput / Answers for Number 4 c')
print ( eigvals )
print ( eigvecs ) 
realeigs = eigvals . real 
print ( realeigs )
lambda1 = eigvals [0]
print ( lambda1 )


[[ 3  0 -2]
 [ 0  1  2]
 [ 0 -2  1]]
Ouput / Answers for Number 2
[3.+0.j 1.+2.j 1.-2.j]
[[1.        +0.j         0.31622777+0.31622777j 0.31622777-0.31622777j]
 [0.        +0.j         0.        -0.63245553j 0.        +0.63245553j]
 [0.        +0.j         0.63245553+0.j         0.63245553-0.j        ]]
[3. 1. 1.]
(3+0j)
[[1.+0.j]
 [0.+0.j]
 [0.+0.j]]
[[3.+0.j]
 [0.+0.j]
 [0.+0.j]]
[[3.+0.j]
 [0.+0.j]
 [0.+0.j]]
[[3.+0.j]
 [0.+0.j]
 [0.+0.j]]
(1+2.0000000000000004j)
[[-0.31622777+0.9486833j ]
 [ 1.26491106-0.63245553j]
 [ 0.63245553+1.26491106j]]
[[-0.31622777+0.9486833j ]
 [ 1.26491106-0.63245553j]
 [ 0.63245553+1.26491106j]]
(1-2.0000000000000004j)
[[0.31622777-0.31622777j]
 [0.        +0.63245553j]
 [0.63245553-0.j        ]]
[[-0.31622777-0.9486833j ]
 [ 1.26491106+0.63245553j]
 [ 0.63245553-1.26491106j]]
[[-0.31622777-0.9486833j ]
 [ 1.26491106+0.63245553j]
 [ 0.63245553-1.26491106j]]
[[1 3]
 [3 1]]
[ 4.+0.j -2.+0.j]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Ouput / A