<a href="https://colab.research.google.com/github/nsaali/ASU-Graduate-Courses/blob/main/Saali_Exam2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Nick Saali LSC 562 Exam 2 / Final Exam

# Number 1

import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
import sympy as sp

# a
A1 = np . array ([[2, -1, 0],[-1, 0, 1],[1, -1, 2]])
print (A1)
eigvals , eigvecs = la.eig(A1)
print(eigvals, eigvecs)

# b

A2 = np . array ([[0, -1, 0, -1],[-1, 0, 1, -2],[1, -1, 0, 1], 
                 [0, 1, 1, 0]])
print (A2)
eigvals , eigvecs = la.eig(A2)
print(eigvals, eigvecs)

# c

A3 = np . random . randint (10 , size = (4 , 4) )
print(A3)
eigvals, eigvecs = la.eig(A3)
print(eigvals, eigvecs)



# Number 2




[[ 2 -1  0]
 [-1  0  1]
 [ 1 -1  2]]
[-0.20556943+0.j          2.10278472+0.66545695j  2.10278472-0.66545695j] [[0.40280325+0.j         0.28362714+0.33935209j 0.28362714-0.33935209j]
 [0.88841055+0.j         0.19667168-0.22362186j 0.19667168+0.22362186j]
 [0.22017321+0.j         0.84599605+0.j         0.84599605-0.j        ]]
[[ 0 -1  0 -1]
 [-1  0  1 -2]
 [ 1 -1  0  1]
 [ 0  1  1  0]]
[-0.62481053+1.30024259j -0.62481053-1.30024259j  0.62481053+0.30024259j
  0.62481053-0.30024259j] [[ 0.47143207+0.25276809j  0.47143207-0.25276809j  0.36365072-0.40727112j
   0.36365072+0.40727112j]
 [ 0.67370786+0.j          0.67370786-0.j          0.18890425-0.0436204j
   0.18890425+0.0436204j ]
 [-0.0504923 +0.21866397j -0.0504923 -0.21866397j -0.58201759+0.j
  -0.58201759-0.j        ]
 [-0.0504923 -0.45504389j -0.0504923 +0.45504389j -0.53839719+0.18890425j
  -0.53839719-0.18890425j]]
[[6 1 1 7]
 [9 2 8 3]
 [9 8 3 3]
 [3 5 8 9]]
[20.937637  +0.j          2.29718742+5.72459337j  2.29718742-5.72459337