<a href="https://colab.research.google.com/github/nsaali/ASU-Graduate-Courses/blob/main/Saali_HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import linalg
'''
A = np.array([[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]])
print("A=", A)
print("First element of first row: A[0][0] =", A[0][0])
print("Third element of second row: A[1][2] =", A[1][2])
print("Last element of last row: A[-1][-1] =", A[-1][-1])
print("First Row: A[0] =", A[0])
print("Third Row: A[2] =", A[2])
print("Last Row: A[-1] =", A[-1])

print("First Column: A[:,0] =", A[:, 0])
print("Fourth Column: A[:,3] =", A[:, 3])
print("Last Column: A[:,-1] =", A[:, -1])
print("first row , all columns: A[:1,]=", A[:1,],)
print("all rows , second column: A[:,2]=", A[:, 2])
print("all rows , third to the fifth column: A[:, 2:5]=", A[:, 2:5])

b1 = np.array([2, 3, 4, 5])
print(b1)
print("Append b1 to A:", np.vstack ((A, b1)))
b2 = np.array([[2], [3], [4]])
print(b2)
print("Append b2 to A:", np.hstack ((A, b2)))
# see https :// numpy.org/doc/stable/ reference /generated /numpy.matrix.html
B1 = np.matrix("1 2; 3 4")
print("B1=", B1)
B2 = np.matrix([[-1, 0], [-3, 4]])
print("B2=", B2)
# Add 1 to each element in B and print it
B3 = B1 + 1
print("Scalar addition: \n ", B3)
print("Scalar addition: \n ", B1 + 1)
print("Element wise addition of two matrices: B1+B2=\n ", B1 + B2)
print("Scalar Product: B1*2= \n ", B1 * 2)
print("Matrix Multiplication: B1*B2=\n ", np.dot(B1 , B2))
print("Matrix Multiplication: B2*B1=\n ", np.dot(B2 , B1))
print("Transpose: \n", B1.transpose ())
print("Trace: \n", B1.trace ())
print("Determinant: \n ", np.linalg.det(B1))
# see https :// docs.scipy.org/doc/scipy/reference /linalg.html
from scipy import linalg
print("Determinant: \n", linalg.det(B1))
print("Inverse: \n", linalg.inv(B1))
A1 = np.matrix([[1, 4], [2, -5]])
b = np.matrix([[3], [-1]])
print("Solve Ax=b: x=\n", linalg.solve(A1, b))
'''
# Number 7
# From 4a
left_side = np.array([[1, 4], [2, -5]])

right_side = np.array([3, -1])
#solve
print(linalg.solve(left_side,right_side))
'''
# From 4b 
left = np.array([[-2, 4], [4, -8]])

right = np.array([3, 1])
#solve
print(linalg.solve(left,right))
# NO SOLUTION for 4b
'''
# Number 8 
#A
a = [2,-3]
b = [-1,4]
matrixA = np.matrix([a,b])
print(matrixA)
print(linalg.det(matrixA))
print(linalg.inv(matrixA))
#B
c = [-2,2]
d = [1,-5]
matrixB = np.matrix([c,d])
print(matrixB)
print(linalg.det(matrixB))
print(linalg.inv(matrixB))
#C
e = [1,2,-3]
f = [0,-1,4]
g = [3,0,2]
matrixC = np.matrix([e,f,g])
print(matrixC)
print(linalg.det(matrixC))
print(linalg.inv(matrixC))
#D
h = [3,-2,2]
i = [-1,1,-5]
j = [0,2,2]
matrixD = np.matrix([h,i,j])
print(matrixD)
print(linalg.det(matrixD))
print(linalg.inv(matrixD))

# Number 9
leftside = np.array([[1,0,-3], [3,1,-2], [2,2,1]])

rightside = np.array([-2,5,4])
#solve
print(linalg.solve(leftside,rightside))



[0.84615385 0.53846154]
[[ 2 -3]
 [-1  4]]
5.0
[[0.8 0.6]
 [0.2 0.4]]
[[-2  2]
 [ 1 -5]]
8.0
[[-0.625 -0.25 ]
 [-0.125 -0.25 ]]
[[ 1  2 -3]
 [ 0 -1  4]
 [ 3  0  2]]
13.0
[[-0.15384615 -0.30769231  0.38461538]
 [ 0.92307692  0.84615385 -0.30769231]
 [ 0.23076923  0.46153846 -0.07692308]]
[[ 3 -2  2]
 [-1  1 -5]
 [ 0  2  2]]
28.0
[[ 0.42857143  0.28571429  0.28571429]
 [ 0.07142857  0.21428571  0.46428571]
 [-0.07142857 -0.21428571  0.03571429]]
[ 4. -3.  2.]
