<a href="https://colab.research.google.com/github/nsaali/ASU-Graduate-Courses/blob/main/Saali_HW6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Number 1
import numpy as np
import matplotlib . pyplot as plt
import scipy . linalg as la
L = np . array ([[0 ,4 , 20 , 55],[.05 ,0 ,0 ,0],[0 ,.25 ,0 , 0],[0 ,0 ,.5 ,0]])
print (L)
x = np . array ([[500],[50],[6],[3]])
L1=np . dot (L ,x)
print ( L1 )
L2=np . dot ( np . linalg . matrix_power (L ,2) ,x )
print ( L2 )
L3=np . dot ( np . linalg . matrix_power (L ,3) ,x )
print ( L3 )
L4=np . dot ( np . linalg . matrix_power (L ,4) ,x )
print ( L4 )
L5=np . dot ( np . linalg . matrix_power (L ,5) ,x )
print ( L5 )
L6=np . dot ( np . linalg . matrix_power (L ,6) ,x )
print ( L6 )
L7=np . dot ( np . linalg . matrix_power (L ,7) ,x )
print ( L7 )
L8=np . dot ( np . linalg . matrix_power (L ,8) ,x )
print ( L8 )
print ([np .sum( L1 ) ,np . sum ( L2 ) , np . sum ( L3 ) ,np .sum( L4 ) ,np . sum ( L5 ) , np . sum ( L6 ) ,
np .sum ( L7 ) ,np . sum ( L8 )]) # observe the total population over the years
eigvals , eigvecs = la . eig (L)
print ( eigvals )
print ( eigvecs )
print (" magnitude of eigenvalues : \n", np . absolute ( eigvals ))

# Number 2

Lf = np . array ([[.434 ,0 ,.56],[.33 ,.61 ,0],[0 ,.304 ,.956 ]])
print ( Lf )
eigvals , eigvecs = la . eig ( Lf )
print (" magnitude of eigenvalues : \n", np . absolute ( eigvals ))
print ("V ( eigenvectors as columns )=", eigvecs )
v= eigvecs [:,-1]
print (" Last column of V:", v) # corresponds to dominant eigenvalue
W=la . inv ( eigvecs )
print ("W= inv (V)=", W)
vright =v/np . sum (v )
wt=W[-1]. real # use . real if the entries are complex - valued
print (" Last Row of Re(W) =", wt )
wleft =wt/wt[0]
print ( np . outer ( vright , wleft )) # needed for outer product
print ( np . dot ( wleft , vright ) ) # inner product , same command as matrix mult
sens =( np . outer ( vright , wleft ) )/np .dot( wleft , vright )
print (" sensitivity matrix is: ", sens )

# Number 3
f2 = 10
f3 = 50
P1 = 0.05
P2 = 0.25
Lf = np . array ([[0, f2, f3],[P1, 0, 0],[0, P2, 0]])
print(Lf)
eigvals , eigvecs = la . eig ( Lf )
print (" magnitude of eigenvalues : \n", np . absolute ( eigvals ))
print ("V ( eigenvectors as columns )=", eigvecs )
v= eigvecs [:,-1]
print (" Last column of V:", v) 
W=la . inv ( eigvecs )
print ("W= inv (V)=", W)
vright =v/np . sum (v )
wt=W[-1].real 
print (" Last Row of Re(W) =", wt )
wleft =wt/wt[0]
print ( np . outer ( vright , wleft )) 
print ( np . dot ( wleft , vright ) ) 
sens =( np . outer ( vright , wleft ) )/np .dot( wleft , vright )
print (" sensitivity matrix is: ", sens )

# Number 4

Lf = np . array ([[0, 0, 1000],[0.02, 0, 0],[0, 0.05, 0]])
print(Lf)
eigvals , eigvecs = la . eig ( Lf )
print (" magnitude of eigenvalues : \n", np . absolute ( eigvals ))
print ("V ( eigenvectors as columns )=", eigvecs )
v= eigvecs [:,-1]
print (" Last column of V:", v) 
W=la . inv ( eigvecs )
print ("W= inv (V)=", W)
vright =v/np . sum (v )
wt=W[-1].real 
print (" Last Row of Re(W) =", wt )
wleft =wt/wt[0]
print ( np . outer ( vright , wleft )) 
print ( np . dot ( wleft , vright ) ) 
sens =( np . outer ( vright , wleft ) )/np .dot( wleft , vright )
print (" sensitivity matrix is: ", sens )

### Interpretation: 
###   The 

[[0.0e+00 4.0e+00 2.0e+01 5.5e+01]
 [5.0e-02 0.0e+00 0.0e+00 0.0e+00]
 [0.0e+00 2.5e-01 0.0e+00 0.0e+00]
 [0.0e+00 0.0e+00 5.0e-01 0.0e+00]]
[[485. ]
 [ 25. ]
 [ 12.5]
 [  3. ]]
[[515.  ]
 [ 24.25]
 [  6.25]
 [  6.25]]
[[565.75  ]
 [ 25.75  ]
 [  6.0625]
 [  3.125 ]]
[[396.125  ]
 [ 28.2875 ]
 [  6.4375 ]
 [  3.03125]]
[[408.61875 ]
 [ 19.80625 ]
 [  7.071875]
 [  3.21875 ]]
[[397.69375  ]
 [ 20.4309375]
 [  4.9515625]
 [  3.5359375]]
[[375.2315625 ]
 [ 19.8846875 ]
 [  5.10773437]
 [  2.47578125]]
[[317.86140625]
 [ 18.76157813]
 [  4.97117188]
 [  2.55386719]]
[525.5, 551.75, 600.6875, 433.88125, 438.715625, 426.61218750000006, 402.699765625, 344.14802343749994]
[ 0.93045348+0.j         -0.71909902+0.j         -0.10567723+0.70893668j
 -0.10567723-0.70893668j]
[[ 0.99842555+0.j          0.9971614 +0.j         -0.99713926+0.j
  -0.99713926-0.j        ]
 [ 0.05365263+0.j         -0.06933408+0.j          0.01025529+0.0687977j
   0.01025529-0.0687977j ]
 [ 0.01441572+0.j          0.024104